SHELL = "/bin/zsh"
CURL = "/usr/bin/curl"
OSASCRIPT = "/usr/bin/osascript"
AWSCLI = "/opt/homebrew/bin/aws"
MAGICK = "/opt/homebrew/bin/magick"
QPDF = "/opt/homebrew/bin/qpdf"
SCREEN = "/opt/homebrew/bin/screen"
GS = "/opt/homebrew/bin/gs"
